### ISSUE TITLE
When you forget to build, error message could be better

### ISSUE THREAD

**Issue by jasonbyrne** [flocasts/flagpole#25]
If you forget to run `flagpole build` and your test is not in the out folder, it just has a system level error like:

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'D:\Users\jason\repos\flagpole-test\tests\out\smoke.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
FAILED TEST SUITE:
D:\Users\jason\repos\flagpole-test\tests\out\smoke.js exited with error code 1
```

This would be better if caught and given a more instructive error message.

**Comment by jasonbyrne** [comment]
This is updated in v2.2.15 and it will now say:

"Suite was not found in the output folder. Did you forget to build?"
