### ISSUE TITLE
2.5.x CLI broken

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#52]
Running any flagpole command after updating global Flagpole NPM results in error

```
/usr/local/lib/node_modules/flagpole/dist/html/domelement.js:16
class DOMElement extends value_1.Value {
                                 ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/flagpole/dist/html/domelement.js:16:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/flagpole/dist/puppeteer/puppeteerelement.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

version 2.5.x

**Comment by jasonbyrne** [comment]
Fixed in 2.5.3
