### ISSUE TITLE
Page errors fail scenario

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#54]
https://github.com/flocasts/flagpole/blob/098c8e5312342c964ae59841368aadcdf0fb42e3/src/scenario.ts#L1063

I think I found the source of a scenario failing on page error. Is there a way to make this an optional failure?

**Comment by johnsickels** [comment]
```
 ✕  Puppeteer got an unexpected page error.
 …  TypeError: Cannot read property 'addEventListener' of null at attachToSelfAndChildren (https://www.milesplit.com/wizard:6:10) at https://www.milesplit.com/wizard:21:5 at https://www.milesplit.com/wizard:22:5
```

**Comment by johnsickels** [comment]
```
 ✕  Puppeteer got an unexpected page error.
 …  TypeError: Cannot read property 'top' of undefined at sidebarStalker (https://www.milesplit.info/js/drivefaze/common.js?build=20200903192536:52:53) at dispatch (https://code.jquery.com/jquery-3.3.1.min.js:2:41772) at y.handle (https://code.jquery.com/jquery-3.3.1.min.js:2:39791)
```

**Comment by johnsickels** [comment]
https://github.com/flocasts/flagpole/commit/62406d943fe65a0e678e17c1fe455657980537d5

**Comment by johnsickels** [comment]
``` ✕  Puppeteer got an unexpected page error.
 …  SyntaxError: Unexpected token '<'```
